### ISSUE TITLE
convert Numpy matrices to Seurat

### ISSUE THREAD

**Issue by nbahlis** [brianhie/scanorama#1]
Can the numpy matrices containing the batch-corrected data sets be converted to Seurat compatible matrices?

**Comment by brianhie** [comment]
There are a couple ways to do this since Seurat is implemented in R and this is implemented in Python.

The reticulate package in RStudio lets you source Python scripts and call them from R (https://github.com/rstudio/reticulate#sourcing-python-scripts).  You may be able to interface with Seurat that way, since currently there's just a couple of scripts (e.g., `bin/scanorama.py`) that do most of the work.

Perhaps a simpler but more resource-inefficient way to do this is to write the batch-corrected matrices to a text file and then reload them into Seurat.  I'd be happy to write a helper function that will let you put data into a file format that can be read into a Seurat object.

**Comment by nbahlis** [comment]
thank you Brian for your quick response. If possible to write a script to help convert the matrices to Seurat compatible that would be great and I believe useful to many in the community. Thanks much again for the great tool!

**Comment by brianhie** [comment]
I wrote a helper function called `save_datasets` in `process.py` that can save a list of batch corrected data sets to a plaintext file (example usage here: https://github.com/brianhie/scanorama/blob/master/bin/293t_jurkat.py#L23)

Obviously not as ideal as doing everything in memory (and the disk files can conceivably get very large), but it might be useful as a quick way to interface between Scanorama and Seurat.

**Comment by cane11** [comment]
This is a bit late. I wanted to share my idea of R code (integration with Seurat) with you and suggest that the new scanorama_r.py could be part of the git version 
(scanorama.py has problems due to __main in source_python("/Users/can/scanorama/build/lib/scanorama/scanorama_r.py").
The preprocessing of the data is done like suggested in the Seurat vignettes (I am using scale.data as input to scanorama and maybe Brian can comment whether another input is more favorable).

```
#Load needed python scripts
library(reticulate)
source_python("/Users/can/scanorama/build/lib/scanorama/scanorama_r.py")
source_python("/Users/can/scanorama/build/lib/scanorama/t_sne_approx.py")
source_python("/Users/can/scanorama/build/lib/scanorama/utils.py")
#Data matrix for Scanorama using non-normalized scaled values
data <- list()
#si and spleen are the corresponding Seurat objects, subsetting selects hvg's
data[[1]] <- as.matrix(t(si@scale.data[hvg_names,]))
data[[2]] <- as.matrix(t(spleen@scale.data[hvg_names,]))
#I get none values when complete columns are zero, I omit them using some threshold
data[[1]][data[[1]]<1e-07] <- 1e-07
data[[2]][data[[2]]<1e-07] <- 1e-07
#hvg_names is the corresponding list of hvg
genes <- list()
genes[[1]] <- hvg_names
genes[[2]] <- hvg_names
#Execute Scanorama
data2 <- r_to_py(data)
genes2 <- r_to_py(genes)
output <- correct(data2, genes2, hvg=hvg_length)
#Convert to new Seurat scaled data elements
corrected_value_1 <- output[[2]][[1]]
corrected_value_2 <- output[[2]][[2]]
corrected_scanorama <- t(rbind(corrected_value_1, corrected_value_2))
data_corr <- r_to_py(corrected_scanorama)
#I changed scanorama.py script at two points
#First delete all elements corresponding to __main (problem with reticulate)
#Second output dimred as first object of correct
corrected_pca_1 <- output[[1]][[1]]
corrected_pca_2 <- output[[1]][[2]]
pca_scanorama <- t(rbind(corrected_pca_1, corrected_pca_2))
#Giving rownames and colnames of the combined dataset using RunCCA or MergeSeurat
rownames(corrected_scanorama) <- output[[3]]
colnames(corrected_scanorama) <- colnames(immune.combined@scale.data)
immune.combined@scale.data <- corrected_scanorama
colnames(pca_scanorama) <- colnames(immune.combined@data)
immune.combined <- SetDimReduction(object = immune.combined, reduction.type = "pca_mnn", slot = "cell.embeddings", new.data = t(pca_scanorama))
immune.combined <- SetDimReduction(object = immune.combined, reduction.type = "pca_mnn", slot = "key", new.data = "pca_mnn")
```

**Comment by cane11** [comment]
I created a pull requested incorporating all the changes I made to scanorama.py to be clearer (and have added in the correct function the possibility to change the PCA dimensions while calling it using 
output <- correct(data2, genes2, hvg=hvg_length, dimred=PCA_dimensions).

I suggest using the PCA from Scanorama because it is faster and Seurat has problems with negativ values in object@scale.data). When you only want the MNN to compute tSNE/clusters I suggest not to use (I have not done in depth testing of other problems related to negative values in Seurat):

`immune.combined@scale.data <- corrected_scanorama`

But only:

```
immune.combined <- SetDimReduction(object = immune.combined, reduction.type = "pca_mnn", slot = "cell.embeddings", new.data = t(pca_scanorama))
immune.combined <- SetDimReduction(object = immune.combined, reduction.type = "pca_mnn", slot = "key", new.data = "pca_mnn")
```

**Comment by cane11** [comment]
@brianhie Could you please comment on using log-normalized and scaled values as input for Scanorama. Would you suggest other preprocessing?
(Scaling to cell cycle score is essential for my further analysis and I think doing it after stitching with Scanorama is not recommended).

**Comment by brianhie** [comment]
@cane11 Scanorama should work with relative expression values (e.g. FPKM or TPM units) or absolute transcript counts (e.g. from UMI experiments).

Would it be possible to regress out cell cycle score and then do the stitching?

**Comment by cane11** [comment]
Thanks. I have implemented it like this using Seurat (Filtering-Normalizing-Scaling Out-Stitching). The results look good, but I wanted to make sure, that this is the sequence you would suggest.

**Comment by mariaprimo** [comment]
@cane11 I'm very interested in trying your code because I have Seurat objects for all my samples. 
You show the example for 2 datasets. Could you explain me how to set it up to compare 6 or 8 datasets? Specially when:
#Convert to new Seurat scaled data elements
corrected_value_1 <- output[[2]][[1]]
corrected_value_2 <- output[[2]][[2]]

and
#Second output dimred as first object of correct
corrected_pca_1 <- output[[1]][[1]]
corrected_pca_2 <- output[[1]][[2]]

I think the rest I should be able to do it on my own. And one more question, what's the difference between scanorama_r.py and scanorama.py?

**Comment by cane11** [comment]
Just use do.call(rbind, corrected_value) and maybe a loop for better readability.
    
```
for (i in folders){
        d <- d+1
        corrected_pca[[d]] <- output[[1]][[d]]
        corrected_value[[d]] <- output[[2]][[d]]
}
corrected_scanorama[[e]] <- t(do.call(rbind,corrected_value))
pca_scanorama[[e]] <- t(do.call(rbind,corrected_pca))
```

On further testing I occasionally get NA error message at:

```
datasets_dimred = assemble(
        datasets_dimred, # Assemble in low dimensional space.
        expr_datasets=datasets, # Modified in place.
        verbose=verbose, knn=KNN, sigma=sigma, approx=APPROX,
        ds_names=ds_names
    )
```

The error happens when expr_datasets and not when datasets_dimred is computed. This can be circumvented, when you only need datasets_dimred (I haven't used the "corrected" gene values until now) by deleting "expr_datasets=datasets", so that as output you only get your corrected PCA values.
