### ISSUE TITLE
Is cell order preserved in corrected data?

### ISSUE THREAD

**Issue by LiBuchauer** [brianhie/scanorama#29]
Hi Brian,

I have a naive question on the the scanorama correction methods. In a test case, I fed data from several batches into the correct() method and then analysed scatterplots of (original data for marker X, scanorama corrected data for marker X) for several genes/markers out of curiousity. I would expect there to be some kind of relationship; not necessairly linear, maybe not even monotonous, not free of noise - but some kind of structure. What I get is fairly wild though and this persists if I look within one batch only. 

I was wandering whether cells/events are still ordererd the same way after scanorama correction as they were before? Or would you think there is some other kind of user error here? Are the many zeros causing problems here - based on what information are they being assigned values during correction?
In principle I thought that the method had worked well, as batches nicely overlayed where they should in PCA and UMAP dimension reductions of the corrected data.

Thanks.

Lisa
![scanorama_question](https://user-images.githubusercontent.com/30862387/51671179-a2659f80-1fc8-11e9-9753-033ac5f75d7e.png)

(blue - all batches, orange - one example batch)

**Comment by brianhie** [comment]
@LiBuchauer thanks for reach out! Scanorama should preserve cell order before and after correction. The plot does look pretty wild (as you say!), but it's hard to tell what's happening without any additional information. You could also try tuning down the smoothing parameter sigma to a lower value (e.g., sigma=1) to see if that helps problems with oversmoothing of the expression values. 

Some other initial questions are: what happens if you do Scanorama correction using just the set of marker genes (or even some set of highly variable genes)?  If you run the marker gene analysis on the corrected data, what is the agreement of the gene sets, if any (same for highly variable genes)?

**Comment by brianhie** [comment]
Hi @LiBuchauer,

I hope you were able to understand what was going on. One thing I forgot to mention is that while Scanorama preserves cell order, it does not preserve gene order (it will sort them lexicographically).

I'm closing the issue but do feel free to reopen if there's a problem in the underlying code.
