### ISSUE TITLE
AnnData import

### ISSUE THREAD

**Issue by s18692001** [brianhie/scanorama#30]
I use two AnnData as the input, but it doesn't work well. For the AnnData I use, the obs is genes, vars is cells. 

After these codes:

`

adatas = [data1, data2]

integrated = scanorama.integrate_scanpy(adatas)

corrected = scanorama.correct_scanpy(adatas)

integrated, corrected = scanorama.correct_scanpy(adatas, return_dimred=True)

`

I got this error:
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-92cf68da3017> in <module>
      3 
      4 # Integration.
----> 5 integrated = scanorama.integrate_scanpy(adatas)
      6 
      7 # Batch correction.

~/anaconda3/envs/cs/lib/python3.6/site-packages/scanorama/scanorama.py in integrate_scanpy(adatas, **kwargs)
    235     """
    236     datasets_dimred, genes = integrate(
--> 237         [adata.X for adata in adatas],
    238         [adata.var_names.values for adata in adatas],
    239         **kwargs

~/anaconda3/envs/cs/lib/python3.6/site-packages/scanorama/scanorama.py in <listcomp>(.0)
    235     """
    236     datasets_dimred, genes = integrate(
--> 237         [adata.X for adata in adatas],
    238         [adata.var_names.values for adata in adatas],
    239         **kwargs

AttributeError: 'function' object has no attribute 'X'
`

**Comment by brianhie** [comment]
Hi @s18692001,

Two things:

Scanorama expects the observation data to be cells and the variables to be genes. So you'd need to transpose your data matrix.

Your error message makes it seem like you aren't passing in a valid AnnData object to the function (hence the "no attribute 'X'" error message). Can you make sure this is a correct object?

Closing issue since this does not appear to be due to an error in the Scanorama code.
