### ISSUE TITLE
correct and assemble methods

### ISSUE THREAD

**Issue by Kyoko-wtnb** [brianhie/scanorama#5]
This is a wonderful method and thank you for sharing the software!!
I am trying to apply for my sets of scRNA-seq data but I've got bit confused when I was trying to understand correct and assemble method.

What I want in the end is expression value of all genes corrected by scanorama. As far as I understand, assemble method (which I assume the main part of scanorama?) is run on low dimension than the original expression value. How can I use this assembled results to correct for entire expression? I got confused because in the correct method, it returns 'datasets' but results of assemble is stored in 'datasets_dimred'. So the output of correct method is output of merge_datasets method. Am I correct? Or am I missing something?
Could you maybe explain how I can get scanorama corrected expression value of all genes exists across all data sets?

I am also wondering if it's ok to mix data sets with different expression values? For example, some of the data sets have row read count, some have UMI count and some have only processed value such as CPM or TPM. I see in the load_name, you do l2 normalization so CPM and TPM are not suitable since they are already corrected for that?

Thank you for your help in advance!!
Best,
Kyoko

**Comment by brianhie** [comment]
I understand how this can be confusing (and I'll update the documentation, since I've been getting a lot of similar questions).

The `correct()` method will do what you want. It uses `assemble()` to find the matches, but it will correct _both_ the reduced dimension data  _and_ the full dimension data if you pass in the `expr_datasets` parameter (this variable is modified in place, somewhat adding to the confusion). `correct()` will return the full gene expression matrix with corrected values.

It should be fine to mix the expression values you mention.

**Comment by Kyoko-wtnb** [comment]
Great, it's clear now. Thank you for your prompt reply!!

Best,
Kyoko
