### ISSUE TITLE
Imputation after scanorama?

### ISSUE THREAD

**Issue by davisidarta** [brianhie/scanorama#51]
Hi!

I understand that scanorama should be used in the very last steps of scRNAseq data analysis. However, Yuval Kluger, a Prof. of Applied Mathematics in Yale, suggested me to run imputation after merging my datasets (I was originally working with Seurat, but the integration yielded poor results).

Is it possible/advisable to run imputation on the output of scanorama? If so, do you have any recommendations regarding how to properly do it?

**Comment by brianhie** [comment]
@davisidarta I'm not completely certain how well I can advise you, since imputation seems to be dataset- and technology-specific and I've done comparatively less work in this particular area. There does seem to be some debate, outside of peer reviewed forums, on the merits of imputation and whether it's needed to correct for zero inflation or whether it artificially introduces data that does not exist (e.g., https://www.biorxiv.org/content/10.1101/582064v1 and https://github.com/theislab/scanpy/issues/189). So it seems like imputation should be used with caution and I've personally never relied on it.

It does seem like most imputation methods are designed to work on the original raw data, so if you really want to use an imputation technique, you would apply it to each raw dataset separately, then use Scanorama to merge the imputed result. Sorry I couldn't give you a more concise or firm answer, but there's still a lot of active and relatively unproven work in this area.
