### ISSUE TITLE
Integrating datasets of different units (FPKM and UMI)

### ISSUE THREAD

**Issue by bazok100** [brianhie/scanorama#62]
Hi, 
I was wondering how to specify that my input datasets are in different units on measures (4 data sets in UMI and one in FPKM). I read in this article- https://www.nature.com/articles/s41587-019-0113-3?proof=true that it is possible to integrate such datasets. I will appreciate any help on how to.

Thanks

**Comment by brianhie** [comment]
Hi @bazok100,

We showed on the pancreas data in that paper that l2-normalization of each cell is sufficient to get good integrative performance. Scanorama automatically applies this normalization so you could just provide log-transformed raw data to the algorithm and see how the results look.

Will close since not an issue with the repository, but feel free to ask any more questions

**Comment by OnlyBelter** [comment]
What's the output should be expected? Is it log-transformed data? I mean if I want to use it for downstream analysis, such as differential expression analysis, then how can I calculate fold change?

What I have seen is that the output values are much smaller than what I input.
