### ISSUE TITLE
How to run different datasets through Scanorama?

### ISSUE THREAD

**Issue by stevedough123** [brianhie/scanorama#72]
Hi,

I'm attempting to integrate spatial data with scRNA-seq using scanorama from this paper (https://www.nature.com/articles/s41587-019-0113-3). I was wondering if it was possible to use csv files as the input rather than the h5 (spatial data) and h5ad (scRNA seq data) files as the input? I currently have csv files with my data of the numeric cluster assignment for each cell in the scRNA seq data and a file with a barcodes by gene counts format. For my spatial data, I have a csv file with spatial locations of the pixels and a file with DGE (gene counts by barcodes) that represents raw counts at each pixel.

**Comment by brianhie** [comment]
Yup! See for example, scanpy's functionality for reading in CSV files: https://scanpy.readthedocs.io/en/stable/api/scanpy.read_csv.html  Scanpy also has some helpful tutorials for general single-cell analysis. Once the CSV files are read into Scanpy, then you can use Scanorama.

Will close issue since not a bug with Scanorama, but happy to answer any more questions
