### ISSUE TITLE
BLAS/LAPACK routine 'DLASWP' gave error code -6

### ISSUE THREAD

**Issue by MagpiePKU** [brianhie/scanorama#76]
Hi,

I have used scanorama through reticulate on a set of Seurat objects basically following the Rscript you provided. On our cluster the code run into such error:

corrected.data <- scanorama$correct(assaylist, genelist, return_dense=TRUE)
Found 60662 genes among all datasets
Error in py_call_impl(callable, dots$args, dots$keywords) :
  BLAS/LAPACK routine 'DLASWP' gave error code -6

The thing is strange that other dependencies on numpy, such as scanpy, scvelo, etc, did not encounter similar issue. We firstly wonder it was a problem with BLAS but np.__config__.show() does not sound abnormal. 

Environment:
R 3.6.2
reticulate_1.16
python 3.8.3 via anaconda 

Thanks a lot!
Best,
Yi

**Comment by brianhie** [comment]
Hi @MagpiePKU, thanks for reaching out! It's unfortunate this fails on the cluster. Scanorama itself is written in pure Python, so any system failures etc. should be an issue with a dependency. Based on the error you described, you should try a few things. See if the scipy.sparse module works on the cluster (e.g., try doing a matrix multiplication or some other operation using sparse matrices in R and reticulate). You might also consider checking if there are architectural differences between your local computer and the cluster (e.g., 32-bit vs 64-bit) and installing dependencies accordingly.

I'll close the issue since it doesn't appear to be an issue with Scanorama itself, but please respond with any more questions and feel free to reopen if you do notice an issue.
