### ISSUE TITLE
about the data after integrarion 

### ISSUE THREAD

**Issue by zcg3721** [brianhie/scanorama#82]
hi,I have a silly question: how can we use the data generated by 
_np.savetxt('data/{}_embedding.txt'.format(NAMESPACE), embedding, delimiter='\t')_
for downstream task analysis or it just for visualization? Is the data generated by this function the result of integration？
thanks.

**Comment by zcg3721** [comment]
another question is **_save_datasets(datasets, genes, data_names)_** in  **_293t_jurkat.py_** 
i found that the output data file is named **_xxxx_corrected.txt_** , but is it corrected ?
it just only  used **_merge_datasets()_** function
looking forward to your reply ,thanks.

**Comment by brianhie** [comment]
Hi @zcg3721, take a look here for a cleaner API that interfaces with scanpy, which also has a brief usage tutorial: https://scanpy.readthedocs.io/en/stable/external/scanpy.external.pp.scanorama_integrate.html#scanpy.external.pp.scanorama_integrate

The result of `scanorama.integrate()` can be used for k-nearest neighbors graph construction and visualization, but we do recommend using a more conservative approach for gene-level analysis tasks (e.g., differential expression analysis). See the discussion here: https://github.com/brianhie/scanorama/issues/79

I'll close since not an issue with Scanorama, but feel free to reopen or ask additional questions.

**Comment by zcg3721** [comment]
@brianhie ok,thank you very much!
